context_providers:
  asana:
    enabled: true
    project_id: "1207751230670395"
    fields:
      Task: "name"
      Task ID: "gid"
      Created At: "created_at"
      Modified At: "modified_at"
      Completed: "completed"
      Assignee: "assignee"
      Due On: "due_on"
      Notes: "notes"
    timezone: "America/Toronto"
  # Add other context providers here
